# This is a basic workflow to help you get started with Actions

name: Compile and publish résumé PDF

on:
  push:
    branches:
        - main
    paths:
        - ".github/workflows/**"
        - "index.html"
        - "resume.tex"
  pull_request:
    branches: 
        - main
    paths:
        - ".github/workflows/**"
        - "index.html"
        - "resume.tex"

jobs:
    build_latex:
        runs-on: ubuntu-latest
        container:
            image: danteev/texlive:latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  persist-credentials: false

            - name: Compile LaTeX document
              uses: xu-cheng/latex-action@v2
              with:
                  root_file: resume.tex
                  extra_fonts: |
                      ./fonts/*.ttf
                  latexmk_use_xelatex: true



            - name: Post Processing
              run: |
                  mkdir build 
                  cp *.pdf build/ 
                  cp index.html build/
            - name: Git add
              run: git add *.pdf

            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@4.1.4
              with:
                  BRANCH: gh-pages
                  FOLDER: build
                  CLEAN: true
